package com.jwl.integration.entity;

// Generated 1.11.2010 0:57:53 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import com.jwl.integration.BaseEntity;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table(name = "attachment")
@NamedQuery(name="Attachment.getByTitle",query="SELECT a FROM Attachment a WHERE a.title=?0")
public class Attachment extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 4688314593729252632L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column(name = "title", nullable = false)
	private String title;
	@Column(name = "originalFileName", nullable = false)
	private String originalFileName;
	@Column(name = "uniqueFileName", nullable = false)
	private String uniqueFileName;
	@Column(name = "description")
	private String description;
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "article_has_attachment", joinColumns = { @JoinColumn(name = "attachment_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "article_id", nullable = false, updatable = false) })
	private Set<Article> articles = new HashSet<Article>(0);

	public Attachment() {
	}

	public Attachment(String title, String originalFileName,
			String uniqueFileName) {
		this.title = title;
		this.originalFileName = originalFileName;
		this.uniqueFileName = uniqueFileName;
	}

	public Attachment(String title, String originalFileName,
			String uniqueFileName, String description, Set<Article> articles) {
		this.title = title;
		this.originalFileName = originalFileName;
		this.uniqueFileName = uniqueFileName;
		this.description = description;
		this.articles = articles;
	}

	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getOriginalFileName() {
		return this.originalFileName;
	}

	public void setOriginalFileName(String originalFileName) {
		this.originalFileName = originalFileName;
	}

	public String getUniqueFileName() {
		return this.uniqueFileName;
	}

	public void setUniqueFileName(String uniqueFileName) {
		this.uniqueFileName = uniqueFileName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
